const safeStorage = {
  data: {},
  getItem(key) {
    try { return localStorage.getItem(key); } catch (e) { return this.data[key] || null; }
  },
  setItem(key, value) {
    try { localStorage.setItem(key, value); } catch (e) { this.data[key] = value; }
  },
  removeItem(key) {
    try { localStorage.removeItem(key); } catch (e) { delete this.data[key]; }
  }
};

const translations = {
  'pt-BR': {
    'dashboard_local_adventures': 'Aventuras Locais',
    'dashboard_online_adventures': 'Aventuras Online',
    'multiplayer_name_required_host': 'Digite seu nome antes de criar a sala.',
    'multiplayer_name_required_join': 'Digite seu nome antes de entrar.',
    'armor_unarmored_con': 'Sem Armadura (10 + DES + CON)',
    'armor_unarmored_wis': 'Sem Armadura (10 + DES + SAB)',
    'armor_leather': 'Couro (11 + DES)',
    'armor_chain_shirt': 'Camisão de Malha + Escudo (16)',
    'armor_chain_mail': 'Cota de Malha (16)',
    'armor_chain_mail_shield': 'Cota de Malha + Escudo (18)',
    'armor_none': 'Nenhuma (10 + DES)',
    'wpn_greataxe': 'Machado Grande',
    'wpn_rapier': 'Rapieira',
    'wpn_warhammer': 'Martelo de Guerra',
    'wpn_scimitar': 'Cimitarra',
    'wpn_longsword': 'Espada Longa',
    'wpn_quarterstaff': 'Bordão',
    'wpn_longbow': 'Arco Longo',
    'wpn_dagger': 'Adaga',
    'eq_barbarian': 'Machado Grande • 4 machadinhas • Pacote de Aventureiro',
    'eq_bard': 'Rapieira • Armadura de couro • Adaga • Pacote de Artista • Instrumento',
    'eq_cleric': 'Martelo de Guerra • Camisão de malha • Escudo • Símbolo Sagrado • Pacote de Sacerdote',
    'eq_druid': 'Escudo de madeira • Cimitarra • Armadura de couro • Pacote de Aventureiro',
    'eq_fighter': 'Espada Longa • Escudo • Cota de malha • Besta leve • Pacote de Explorador',
    'eq_monk': 'Espada curta • Bordão • Pacote de Explorador',
    'eq_paladin': 'Espada Longa • Escudo • Cota de malha • Símbolo Sagrado • Pacote de Sacerdote',
    'eq_ranger': 'Arco Longo • 20 flechas • Armadura de couro • Espada curta • Pacote de Aventureiro',
    'eq_rogue': 'Rapieira • Arco curto • 20 flechas • Armadura de couro • Ferramentas de Ladrão • Pacote de Arrombador',
    'eq_sorcerer': 'Besta leve • 20 virotes • Adaga • Bolsa de componentes • Pacote de Explorador',
    'eq_warlock': 'Besta leve • 20 virotes • Armadura de couro • Adaga • Foco arcano • Pacote de Estudioso',
    'eq_wizard': 'Bordão • Adaga • Bolsa de componentes • Pacote de Estudioso • Livro de Magias',
    'prof_barbarian': 'Armaduras Leves e Médias, Escudos, Armas Simples e Marciais',
    'prof_bard': 'Armaduras Leves, Armas Simples, Bestas de mão, Espadas longas, Rapieiras, Instrumentos',
    'prof_cleric': 'Armaduras Leves e Médias, Escudos, Armas Simples',
    'prof_druid': 'Armaduras Leves e Médias, Escudos, Armas Simples, Kit de Herbalismo',
    'prof_fighter': 'Todas as armaduras, Escudos, Armas Simples e Marciais',
    'prof_monk': 'Armas Simples, Espadas curtas, Escolha 1 ferramenta de artesão',
    'prof_paladin': 'Todas as armaduras, Escudos, Armas Simples e Marciais',
    'prof_ranger': 'Armaduras Leves e Médias, Escudos, Armas Simples e Marciais',
    'prof_rogue': 'Armaduras Leves, Armas Simples, Bestas de mão, Espadas longas, Rapieiras, Ferramentas de Ladrão',
    'prof_sorcerer': 'Adagas, Dardos, Fundas, Bordões, Bestas leves',
    'prof_warlock': 'Armaduras Leves, Armas Simples',
    'prof_wizard': 'Adagas, Dardos, Fundas, Bordões, Bestas leves',
    'feat_barbarian': 'Fúria (2/dia), Defesa sem Armadura, Sentido de Perigo',
    'feat_bard': 'Inspiração de Bardo (d6), Conjuração, Conjuração de Ritual',
    'feat_cleric': 'Conjuração, Domínio Divino (Vida), Canalizar Divindade (1/descanso)',
    'feat_druid': 'Druídico, Conjuração, Forma Selvagem (2/descanso)',
    'feat_fighter': 'Estilo de Luta (Defesa), Retomar o Fôlego, Surto de Ação',
    'feat_monk': 'Defesa sem Armadura, Artes Marciais (1d4), Ki (2 pontos), Rajada de Golpes',
    'feat_paladin': 'Sentido Divino, Cura pelas Mãos (5 PV), Estilo de Luta, Destruição Divina',
    'feat_ranger': 'Inimigo Favorito, Explorador Natural, Estilo de Luta (Arquearia)',
    'feat_rogue': 'Especialização, Ataque Furtivo (1d6), Gíria de Ladrão, Ação Astuta',
    'feat_sorcerer': 'Conjuração, Origem Feiticeira (Linhagem Dracônica), Fonte de Magia (2 pontos)',
    'feat_warlock': 'Patrono Extra-Terreno (O Corruptor), Magia de Pacto (1 espaço), Invocação Mística',
    'feat_wizard': 'Conjuração, Recuperação Arcana, Livro de Magias',
    'spell_vicious_mockery': 'Zombaria Viciosa',
    'spell_prestidigitation': 'Prestidigitação',
    'spell_healing_word': 'Palavra Curativa',
    'spell_thunderwave': 'Onda de Trovejante',
    'spell_charm_person': 'Enfeitiçar Pessoa',
    'spell_light': 'Luz',
    'spell_sacred_flame': 'Chama Sagrada',
    'spell_guidance': 'Orientação',
    'spell_cure_wounds': 'Curar Ferimentos',
    'spell_bless': 'Bênção',
    'spell_guiding_bolt': 'Raio Guiador',
    'spell_druidcraft': 'Druidismo',
    'spell_produce_flame': 'Produzir Chama',
    'spell_shillelagh': 'Bordão Mágico',
    'spell_entangle': 'Constrição',
    'spell_faerie_fire': 'Fogo das Fadas',
    'spell_lay_on_hands': 'Cura pelas Mãos',
    'spell_thunderous_smite': 'Destruição Trovejante',
    'spell_hunters_mark': 'Marca do Caçador',
    'spell_speak_with_animals': 'Falar com Animais',
    'spell_fire_bolt': 'Raio de Fogo',
    'spell_minor_illusion': 'Ilusão Menor',
    'spell_ray_of_frost': 'Raio de Gelo',
    'spell_magic_missile': 'Mísseis Mágicos',
    'spell_shield': 'Escudo Arcano',
    'spell_sleep': 'Sono',
    'spell_eldritch_blast': 'Rajada Mística',
    'spell_mage_hand': 'Mãos Mágicas',
    'spell_chill_touch': 'Toque Arrepiante',
    'spell_hex': 'Desgraça',
    'spell_witch_bolt': 'Raio Bruxo',
    'spell_arms_of_hadar': 'Braços de Hadar',
    'spell_mage_armor': 'Armadura Arcana',
    'spell_burning_hands': 'Mãos Flamejantes',
    'bg_desc_acolyte': 'Chamado sagrado e rituais sagrados.',
    'bg_desc_criminal': 'Contatos criminosos e ferramentas de ladrão.',
    'bg_desc_folk_hero': 'Herói do povo de uma vila.',
    'bg_desc_hermit': 'Vida de isolamento e descoberta.',
    'bg_desc_noble': 'De linhagem nobre.',
    'bg_desc_outlander': 'Criado nos ermos.',
    'bg_desc_sage': 'Pesquisador e acadêmico.',
    'bg_desc_sailor': 'Marinheiro e navegador.',
    'bg_desc_soldier': 'Veterano de um exército.',
    'bg_desc_urchin': 'Sobrevivente das ruas.',
    'gen_skills_tools': 'perícias e ferramentas',
    'gen_backstory_template': 'Um {race} {class} com origem de {background}.',
    subtitle: "Gerencie seus heróis e suas histórias",
    btn_create: "Criar Novo Personagem",
    btn_back: "Voltar",
    btn_export_pdf: "PDF",
    btn_export_json: "JSON",
    btn_import: "Importar",
    btn_save: "Salvar",

    ph_char_name: "Nome do Personagem",
    ph_class: "Classe",
    ph_subclass: "Subclasse",
    ph_race: "Raça",
    ph_bg: "Antecedente",
    ph_align: "Alinhamento",
    ph_level: "Nível",

    lbl_class: "Classe",
    lbl_level: "Nível",
    lbl_race: "Raça",
    lbl_bg: "Antecedente",
    lbl_subclass: "Subclasse",
    lbl_align: "Alinhamento",

    attr_str: "FOR", attr_dex: "DES", attr_con: "CON",
    attr_int: "INT", attr_wis: "SAB", attr_cha: "CAR",

    lbl_inspiration: "Inspiração",
    lbl_prof_bonus: "Bônus Prof.",
    lbl_passive_perc: "Percepção Passiva",
    lbl_ac: "CA",
    lbl_init: "Iniciativa",
    lbl_speed: "Deslocamento",

    lbl_hp_title: "Pontos de Vida",
    lbl_hp_max: "Máximo",
    lbl_hp_curr: "Atual",
    lbl_hp_temp: "Temp",
    lbl_hit_dice: "Dados de Vida",
    lbl_death_saves: "Testes contra Morte",
    lbl_success: "Sucesso",
    lbl_fail: "Falha",

    lbl_saves_title: "Resistências",
    save_str: "Força", save_dex: "Destreza", save_con: "Constituição",
    save_int: "Inteligência", save_wis: "Sabedoria", save_cha: "Carisma",

    lbl_skills_title: "Perícias",
    skill_acro: "Acrobacia", skill_anim: "Adestrar Animais", skill_arca: "Arcanismo",
    skill_athl: "Atletismo", skill_perf: "Atuação", skill_decp: "Enganação",
    skill_stea: "Furtividade", skill_hist: "História", skill_inti: "Intimidação",
    skill_insg: "Intuição", skill_invs: "Investigação", skill_medi: "Medicina",
    skill_natu: "Natureza", skill_perc: "Percepção", skill_pers: "Persuasão",
    skill_slei: "Prestidigitação", skill_reli: "Religião", skill_surv: "Sobrevivência",

    tab_attacks: "Ataques",
    tab_equip: "Equipamento",
    tab_traits: "Traços",

    lbl_attacks_desc: "Ataques e Conjuração",
    hlp_attacks: "Nome | Bônus | Dano/Tipo",
    ph_attacks: "Ex: Espada Longa | +5 | 1d8+3 cortante",
    lbl_equip: "Equipamento",
    ph_equip: "Liste seus itens...",
    lbl_prof_lang: "Proficiências e Idiomas",
    ph_prof_lang: "Armaduras, armas, ferramentas, idiomas...",
    lbl_feat_traits: "Características e Talentos",
    ph_feat_traits: "Descreva suas habilidades especiais...",

    sec_spells: "Magias",
    lbl_spell_ability: "Hab.",
    lbl_spell_dc: "CD",
    lbl_spell_atk: "Atq.",
    lbl_cantrips: "Truques",
    lbl_level_x: "Nível",
    ph_spells_list: "Um por linha",

    sec_backstory: "História do Personagem",
    ph_backstory: "Conte a história do seu personagem...",

    footer_text: "Copyright © 2025 criado por levirenato.",

    msg_saved: "Salvo!",
    msg_confirm_delete: "ATENÇÃO: Deseja apagar esta ficha?",
    msg_confirm_overwrite: "Deseja substituir os dados do personagem atual?",
    msg_imported: "Personagem importado!",
    msg_updated: "Personagem atualizado!",
    msg_char_not_found: "Nenhum herói encontrado.",

    modal_title_info: "Aviso",
    modal_title_confirm: "Confirmação",
    modal_title_success: "Sucesso",
    modal_title_error: "Erro",
    modal_confirm: "Confirmar",
    modal_cancel: "Cancelar",

    msg_no_char_loaded: "Nenhum personagem carregado!",
    msg_char_data_error: "Erro ao encontrar dados do personagem.",
    msg_pdf_success: "PDF exportado com sucesso!",
    msg_pdf_generating: "Gerando...",
    msg_json_error: "Erro ao processar o arquivo JSON.",
    msg_unsaved_changes: "Você tem alterações não salvas. Deseja sair sem salvar?",
    msg_player: "Jogador",

    coin_cp: "PC",
    coin_sp: "PP",
    coin_ep: "PE",
    coin_gp: "PO",
    coin_pp: "PL",

    lbl_unknown: "Desconhecido",
    lbl_default_race: "Raça",
    lbl_default_class: "Classe",

    mp_title: "Multiplayer (Teste)",
    mp_btn_host: "Criar Sala",
    mp_btn_join: "Entrar",
    mp_btn_ping_all: "Broadcast",
    mp_btn_ping_host: "Ping Mestre",
    mp_btn_leave: "Sair",
    mp_name_ph: "Seu Nome",
    mp_room_ph: "Código da Sala",
    mp_status: "Status",
    mp_code: "Código",
    mp_players: "Jogadores",

    mp_msg_active_session: "Já existe uma sessão ativa. Saia antes de continuar.",
    mp_msg_room_created: "Sala criada! Código: {code}",
    mp_msg_invalid_code: "Código inválido. Use 6 letras/números.",
    mp_msg_joined_room: "Conectado à sala {code}",
    mp_msg_player_joined: "Jogador conectado! ({count} online)",
    mp_msg_player_left: "Jogador desconectado. ({count} online)",
    mp_msg_conn_closed: "Conexão com o Mestre encerrada.",
    mp_msg_conn_error: "Erro de conexão: {msg}",
    mp_msg_peer_error: "Erro: {msg}",
    mp_msg_broadcast_sent: "Broadcast enviado para {count} jogador(es).",
    mp_msg_sent_to_host: "Mensagem enviada ao Mestre.",
    mp_msg_broadcast_host_only: "Só o Mestre pode fazer broadcast.",
    mp_msg_send_player_only: "Só o Jogador pode usar send().",
    mp_msg_no_conn: "Sem conexão com o Mestre.",
    mp_msg_session_closed: "Sessão encerrada.",
    mp_msg_received: "Recebido: {data}",

    mp_party_title: "Mesa do Mestre",
    mp_col_player: "Jogador",
    mp_col_ac: "CA",
    mp_col_hp: "HP",
    mp_col_action: "Ações",
    mp_party_empty: "Nenhum jogador conectado.",
    mp_btn_send_sheet: "Enviar Ficha",
    mp_btn_send_sheet_tip: "Envia a ficha atual para o Mestre.",
    mp_btn_damage: "Dano",
    mp_btn_heal: "Cura",
    mp_msg_sheet_sent: "Ficha enviada ao Mestre.",
    mp_msg_sheet_received: "Ficha de {name} recebida.",
    mp_msg_sheet_accepted: "Ficha aceita. O Mestre agora controla o HP.",
    mp_msg_hp_updated: "HP de {name} atualizado: {hp}",
    mp_msg_hp_locked: "HP travado pelo Mestre.",
    mp_msg_no_char: "Carregue uma ficha antes de enviá-la ao Mestre.",
    mp_msg_state_received: "Estado de combate recebido do Mestre.",

    gen_title: "Gerador Rápido",
    gen_tagline: "Crie um herói pronto para a aventura em segundos.",
    gen_btn_open: "Gerador Rápido",
    gen_name_label: "Nome",
    gen_random_name: "Nome aleatório",
    gen_race_label: "Raça",
    gen_race_random: "Aleatória",
    gen_level_label: "Nível",
    gen_method_label: "Método de atributos",
    gen_method_standard: "Array padrão (15, 14, 13, 12, 10, 8)",
    gen_method_roll: "Rolar 4d6 (descarta o menor)",
    gen_mode_label: "Modo de geração",
    gen_mode_archetype: "Arquétipo pronto",
    gen_mode_random: "Tudo aleatório",
    gen_roll_btn: "Rolar atributos",
    gen_roll_again: "Rolar novamente",
    gen_create_btn: "Criar ficha",
    gen_cancel_btn: "Cancelar",
    gen_class_pick: "Escolha seu arquétipo",
    gen_generated: "Ficha criada!",
    gen_rolling: "Rolando dados...",
    gen_preview_title: "Prévia",
    gen_random_hint: "Classe, raça, nome e atributos serão sorteados para você.",
    gen_archetype_hint: "Escolha uma classe pronta; os atributos serão distribuídos conforme o papel dela.",
    gen_alignment_label: "Alinhamento",
    gen_theme_label: "Cor do tema",
    gen_background_label: "Antecedente",
    gen_missing_name: "Digite um nome ou sorteie um.",
    gen_attr_total: "Total",

    cls_barbarian: "Bárbaro", cls_bard: "Bardo", cls_cleric: "Clérigo",
    cls_druid: "Druida", cls_fighter: "Guerreiro", cls_monk: "Monge",
    cls_paladin: "Paladino", cls_ranger: "Patrulheiro", cls_rogue: "Ladino",
    cls_sorcerer: "Feiticeiro", cls_warlock: "Bruxo", cls_wizard: "Mago",

    race_human: "Humano", race_dwarf: "Anão", race_elf: "Elfo",
    race_halfling: "Halfling", race_gnome: "Gnomo", race_half_orc: "Meio-Orc",
    race_dragonborn: "Dragônat", race_tiefling: "Tiefling",
    race_half_elf: "Meio-Elfo", race_aasimar: "Aasimar",

    bg_acolyte: "Acólito", bg_criminal: "Criminoso", bg_folk_hero: "Herói do Povo",
    bg_hermit: "Eremita", bg_noble: "Nobre", bg_outlander: "Forasteiro",
    bg_sage: "Sábio", bg_sailor: "Marinheiro", bg_soldier: "Soldado",
    bg_urchin: "Pequeno Marginal",

    align_lg: "Leal e Bom", align_ng: "Neutro e Bom", align_cg: "Caótico e Bom",
    align_ln: "Leal e Neutro", align_n: "Neutro", align_cn: "Caótico e Neutro",
    align_le: "Leal e Mau", align_ne: "Neutro e Mau", align_ce: "Caótico e Mau"
  },
  'en-US': {
    'dashboard_local_adventures': 'Local Adventures',
    'dashboard_online_adventures': 'Online Adventures',
    'multiplayer_name_required_host': 'Enter your name before creating a room.',
    'multiplayer_name_required_join': 'Enter your name before joining.',
    'armor_unarmored_con': 'Unarmored (10 + DEX + CON)',
    'armor_unarmored_wis': 'Unarmored (10 + DEX + WIS)',
    'armor_leather': 'Leather (11 + DEX)',
    'armor_chain_shirt': 'Chain Shirt + Shield (16)',
    'armor_chain_mail': 'Chain mail (16)',
    'armor_chain_mail_shield': 'Chain mail + Shield (18)',
    'armor_none': 'None (10 + DEX)',
    'wpn_greataxe': 'Greataxe',
    'wpn_rapier': 'Rapier',
    'wpn_warhammer': 'Warhammer',
    'wpn_scimitar': 'Scimitar',
    'wpn_longsword': 'Longsword',
    'wpn_quarterstaff': 'Quarterstaff',
    'wpn_longbow': 'Longbow',
    'wpn_dagger': 'Dagger',
    'eq_barbarian': 'Greataxe • 4 handaxes • Explorer Pack',
    'eq_bard': 'Rapier • Leather armor • Dagger • Entertainer Pack • Instrument',
    'eq_cleric': 'Warhammer • Chain Shirt • Shield • Holy Symbol • Priest Pack',
    'eq_druid': 'Wooden shield • Scimitar • Leather armor • Explorer Pack',
    'eq_fighter': 'Longsword • Shield • Chain mail • Light crossbow • Dungeoneer Pack',
    'eq_monk': 'Shortsword • Quarterstaff • Dungeoneer Pack',
    'eq_paladin': 'Longsword • Shield • Chain mail • Holy Symbol • Priest Pack',
    'eq_ranger': 'Longbow • 20 arrows • Leather armor • Shortsword • Explorer Pack',
    'eq_rogue': 'Rapier • Shortbow • 20 arrows • Leather armor • Thieves\' Tools • Burglar Pack',
    'eq_sorcerer': 'Light crossbow • 20 bolts • Dagger • Component pouch • Dungeoneer Pack',
    'eq_warlock': 'Light crossbow • 20 bolts • Leather armor • Dagger • Arcane focus • Scholar Pack',
    'eq_wizard': 'Quarterstaff • Dagger • Component pouch • Scholar Pack • Spellbook',
    'prof_barbarian': 'Light & Medium armor, Shields, Simple & Martial weapons',
    'prof_bard': 'Light armor, Simple weapons, Hand crossbows, Longswords, Rapiers, Instruments',
    'prof_cleric': 'Light & Medium armor, Shields, Simple weapons',
    'prof_druid': 'Light & Medium armor, Shields, Simple weapons, Herbalism kit',
    'prof_fighter': 'All armor, Shields, Simple & Martial weapons',
    'prof_monk': 'Simple weapons, Shortswords, Choose 1 artisan tool',
    'prof_paladin': 'All armor, Shields, Simple & Martial weapons',
    'prof_ranger': 'Light & Medium armor, Shields, Simple & Martial weapons',
    'prof_rogue': 'Light armor, Simple weapons, Hand crossbows, Longswords, Rapiers, Thieves\' tools',
    'prof_sorcerer': 'Daggers, Darts, Slings, Quarterstaffs, Light crossbows',
    'prof_warlock': 'Light armor, Simple weapons',
    'prof_wizard': 'Daggers, Darts, Slings, Quarterstaffs, Light crossbows',
    'feat_barbarian': 'Rage (2/day), Unarmored Defense, Danger Sense',
    'feat_bard': 'Bardic Inspiration (d6), Spellcasting, Ritual Casting',
    'feat_cleric': 'Spellcasting, Divine Domain (Life), Channel Divinity (1/rest)',
    'feat_druid': 'Druidic, Spellcasting, Wild Shape (2/rest)',
    'feat_fighter': 'Fighting Style (Defense), Second Wind, Action Surge',
    'feat_monk': 'Unarmored Defense, Martial Arts (1d4), Ki (2 points), Flurry of Blows',
    'feat_paladin': 'Divine Sense, Lay on Hands (5 HP), Fighting Style, Divine Smite',
    'feat_ranger': 'Favored Enemy, Natural Explorer, Fighting Style (Archery)',
    'feat_rogue': 'Expertise, Sneak Attack (1d6), Thieves\' Cant, Cunning Action',
    'feat_sorcerer': 'Spellcasting, Sorcerous Origin (Draconic Bloodline), Font of Magic (2 points)',
    'feat_warlock': 'Otherworldly Patron (The Fiend), Pact Magic (1 slot), Eldritch Invocation',
    'feat_wizard': 'Spellcasting, Arcane Recovery, Spellbook',
    'spell_vicious_mockery': 'Vicious Mockery',
    'spell_prestidigitation': 'Prestidigitation',
    'spell_healing_word': 'Healing Word',
    'spell_thunderwave': 'Thunderwave',
    'spell_charm_person': 'Charm Person',
    'spell_light': 'Light',
    'spell_sacred_flame': 'Sacred Flame',
    'spell_guidance': 'Guidance',
    'spell_cure_wounds': 'Cure Wounds',
    'spell_bless': 'Bless',
    'spell_guiding_bolt': 'Guiding Bolt',
    'spell_druidcraft': 'Druidcraft',
    'spell_produce_flame': 'Produce Flame',
    'spell_shillelagh': 'Shillelagh',
    'spell_entangle': 'Entangle',
    'spell_faerie_fire': 'Faerie Fire',
    'spell_lay_on_hands': 'Lay on Hands',
    'spell_thunderous_smite': 'Thunderous Smite',
    'spell_hunters_mark': 'Hunter\'s Mark',
    'spell_speak_with_animals': 'Speak with Animals',
    'spell_fire_bolt': 'Fire Bolt',
    'spell_minor_illusion': 'Minor Illusion',
    'spell_ray_of_frost': 'Ray of Frost',
    'spell_magic_missile': 'Magic Missile',
    'spell_shield': 'Shield',
    'spell_sleep': 'Sleep',
    'spell_eldritch_blast': 'Eldritch Blast',
    'spell_mage_hand': 'Mage Hand',
    'spell_chill_touch': 'Chill Touch',
    'spell_hex': 'Hex',
    'spell_witch_bolt': 'Witch Bolt',
    'spell_arms_of_hadar': 'Arms of Hadar',
    'spell_mage_armor': 'Mage Armor',
    'spell_burning_hands': 'Burning Hands',
    'bg_desc_acolyte': 'Sacred call & holy rituals.',
    'bg_desc_criminal': 'Criminal contacts & thief tools.',
    'bg_desc_folk_hero': 'Folk hero of a village.',
    'bg_desc_hermit': 'Life of seclusion & discovery.',
    'bg_desc_noble': 'Of noble lineage.',
    'bg_desc_outlander': 'Raised in the wild.',
    'bg_desc_sage': 'Researcher & scholar.',
    'bg_desc_sailor': 'Seafarer & navigator.',
    'bg_desc_soldier': 'Veteran of a military.',
    'bg_desc_urchin': 'Street survivor.',
    'gen_skills_tools': 'skills & tools',
    'gen_backstory_template': 'A {race} {class} with {background} background.',
    subtitle: "Manage your heroes and their stories",
    btn_create: "Create New Character",
    btn_back: "Back",
    btn_export_pdf: "PDF",
    btn_export_json: "JSON",
    btn_import: "Import",
    btn_save: "Save",

    ph_char_name: "Character Name",
    ph_class: "Class",
    ph_subclass: "Subclass",
    ph_race: "Race",
    ph_bg: "Background",
    ph_align: "Alignment",
    ph_level: "Level",

    lbl_class: "Class",
    lbl_level: "Level",
    lbl_race: "Race",
    lbl_bg: "Background",
    lbl_subclass: "Subclass",
    lbl_align: "Alignment",

    attr_str: "STR", attr_dex: "DEX", attr_con: "CON",
    attr_int: "INT", attr_wis: "WIS", attr_cha: "CHA",

    lbl_inspiration: "Inspiration",
    lbl_prof_bonus: "Prof. Bonus",
    lbl_passive_perc: "Passive Perception",
    lbl_ac: "AC",
    lbl_init: "Initiative",
    lbl_speed: "Speed",

    lbl_hp_title: "Hit Points",
    lbl_hp_max: "Max",
    lbl_hp_curr: "Current",
    lbl_hp_temp: "Temp",
    lbl_hit_dice: "Hit Dice",
    lbl_death_saves: "Death Saves",
    lbl_success: "Success",
    lbl_fail: "Failure",

    lbl_saves_title: "Saving Throws",
    save_str: "Strength", save_dex: "Dexterity", save_con: "Constitution",
    save_int: "Intelligence", save_wis: "Wisdom", save_cha: "Charisma",

    lbl_skills_title: "Skills",
    skill_acro: "Acrobatics", skill_anim: "Animal Handling", skill_arca: "Arcana",
    skill_athl: "Athletics", skill_perf: "Performance", skill_decp: "Deception",
    skill_stea: "Stealth", skill_hist: "History", skill_inti: "Intimidation",
    skill_insg: "Insight", skill_invs: "Investigation", skill_medi: "Medicine",
    skill_natu: "Nature", skill_perc: "Perception", skill_pers: "Persuasion",
    skill_slei: "Sleight of Hand", skill_reli: "Religion", skill_surv: "Survival",

    tab_attacks: "Attacks",
    tab_equip: "Equipment",
    tab_traits: "Traits",

    lbl_attacks_desc: "Attacks & Spellcasting",
    hlp_attacks: "Name | Bonus | Damage/Type",
    ph_attacks: "Ex: Longsword | +5 | 1d8+3 slashing",
    lbl_equip: "Equipment",
    ph_equip: "List your items...",
    lbl_prof_lang: "Proficiencies & Languages",
    ph_prof_lang: "Armor, weapons, tools, languages...",
    lbl_feat_traits: "Features & Traits",
    ph_feat_traits: "Describe your special abilities...",

    sec_spells: "Spells",
    lbl_spell_ability: "Abil.",
    lbl_spell_dc: "DC",
    lbl_spell_atk: "Atk.",
    lbl_cantrips: "Cantrips",
    lbl_level_x: "Level",
    ph_spells_list: "One per line",

    sec_backstory: "Character Backstory",
    ph_backstory: "Tell your character's story...",

    footer_text: "Copyright © 2025 created by levirenato.",

    msg_saved: "Saved!",
    msg_confirm_delete: "WARNING: Do you want to delete this sheet?",
    msg_confirm_overwrite: "Do you want to overwrite current character data?",
    msg_imported: "Character imported!",
    msg_updated: "Character updated!",
    msg_char_not_found: "No heroes found.",

    modal_title_info: "Notice",
    modal_title_confirm: "Confirmation",
    modal_title_success: "Success",
    modal_title_error: "Error",
    modal_confirm: "Confirm",
    modal_cancel: "Cancel",

    msg_no_char_loaded: "No character loaded!",
    msg_char_data_error: "Error finding character data.",
    msg_pdf_success: "PDF exported successfully!",
    msg_pdf_generating: "Generating...",
    msg_json_error: "Error processing JSON file.",
    msg_unsaved_changes: "You have unsaved changes. Leave without saving?",
    msg_player: "Player",

    coin_cp: "CP",
    coin_sp: "SP",
    coin_ep: "EP",
    coin_gp: "GP",
    coin_pp: "PP",

    lbl_unknown: "Unknown",
    lbl_default_race: "Race",
    lbl_default_class: "Class",

    mp_title: "Multiplayer (Test)",
    mp_btn_host: "Host Room",
    mp_btn_join: "Join",
    mp_btn_ping_all: "Broadcast",
    mp_btn_ping_host: "Ping Host",
    mp_btn_leave: "Leave",
    mp_name_ph: "Your Name",
    mp_room_ph: "Room Code",
    mp_status: "Status",
    mp_code: "Code",
    mp_players: "Players",

    mp_msg_active_session: "An active session already exists. Leave first.",
    mp_msg_room_created: "Room created! Code: {code}",
    mp_msg_invalid_code: "Invalid code. Use 6 letters/numbers.",
    mp_msg_joined_room: "Connected to room {code}",
    mp_msg_player_joined: "Player connected! ({count} online)",
    mp_msg_player_left: "Player disconnected. ({count} online)",
    mp_msg_conn_closed: "Connection to the Master ended.",
    mp_msg_conn_error: "Connection error: {msg}",
    mp_msg_peer_error: "Error: {msg}",
    mp_msg_broadcast_sent: "Broadcast sent to {count} player(s).",
    mp_msg_sent_to_host: "Message sent to the Master.",
    mp_msg_broadcast_host_only: "Only the Master can broadcast.",
    mp_msg_send_player_only: "Only the Player can use send().",
    mp_msg_no_conn: "No connection to the Master.",
    mp_msg_session_closed: "Session closed.",
    mp_msg_received: "Received: {data}",

    mp_party_title: "Master's Table",
    mp_col_player: "Player",
    mp_col_ac: "AC",
    mp_col_hp: "HP",
    mp_col_action: "Actions",
    mp_party_empty: "No players connected.",
    mp_btn_send_sheet: "Send Sheet",
    mp_btn_send_sheet_tip: "Send the current sheet to the Master.",
    mp_btn_damage: "Damage",
    mp_btn_heal: "Heal",
    mp_msg_sheet_sent: "Sheet sent to the Master.",
    mp_msg_sheet_received: "Received {name}'s sheet.",
    mp_msg_sheet_accepted: "Sheet accepted. The Master now controls your HP.",
    mp_msg_hp_updated: "{name}'s HP updated: {hp}",
    mp_msg_hp_locked: "HP locked by the Master.",
    mp_msg_no_char: "Load a sheet before sending it to the Master.",
    mp_msg_state_received: "Combat state received from the Master.",

    gen_title: "Quick Generator",
    gen_tagline: "Create an adventure-ready hero in seconds.",
    gen_btn_open: "Quick Generator",
    gen_name_label: "Name",
    gen_random_name: "Random name",
    gen_race_label: "Race",
    gen_race_random: "Random",
    gen_level_label: "Level",
    gen_method_label: "Ability method",
    gen_method_standard: "Standard array (15, 14, 13, 12, 10, 8)",
    gen_method_roll: "Roll 4d6 (drop lowest)",
    gen_mode_label: "Generation mode",
    gen_mode_archetype: "Ready-made archetype",
    gen_mode_random: "Fully random",
    gen_roll_btn: "Roll abilities",
    gen_roll_again: "Roll again",
    gen_create_btn: "Create sheet",
    gen_cancel_btn: "Cancel",
    gen_class_pick: "Choose your archetype",
    gen_generated: "Sheet created!",
    gen_rolling: "Rolling dice...",
    gen_preview_title: "Preview",
    gen_random_hint: "Class, race, name and abilities will be drawn for you.",
    gen_archetype_hint: "Pick a ready-made class; abilities are distributed to fit its role.",
    gen_alignment_label: "Alignment",
    gen_theme_label: "Theme color",
    gen_background_label: "Background",
    gen_missing_name: "Type a name or roll one.",
    gen_attr_total: "Total",

    cls_barbarian: "Barbarian", cls_bard: "Bard", cls_cleric: "Cleric",
    cls_druid: "Druid", cls_fighter: "Fighter", cls_monk: "Monk",
    cls_paladin: "Paladin", cls_ranger: "Ranger", cls_rogue: "Rogue",
    cls_sorcerer: "Sorcerer", cls_warlock: "Warlock", cls_wizard: "Wizard",

    race_human: "Human", race_dwarf: "Dwarf", race_elf: "Elf",
    race_halfling: "Halfling", race_gnome: "Gnome", race_half_orc: "Half-Orc",
    race_dragonborn: "Dragonborn", race_tiefling: "Tiefling",
    race_half_elf: "Half-Elf", race_aasimar: "Aasimar",

    bg_acolyte: "Acolyte", bg_criminal: "Criminal", bg_folk_hero: "Folk Hero",
    bg_hermit: "Hermit", bg_noble: "Noble", bg_outlander: "Outlander",
    bg_sage: "Sage", bg_sailor: "Sailor", bg_soldier: "Soldier",
    bg_urchin: "Urchin",

    align_lg: "Lawful Good", align_ng: "Neutral Good", align_cg: "Chaotic Good",
    align_ln: "Lawful Neutral", align_n: "Neutral", align_cn: "Chaotic Neutral",
    align_le: "Lawful Evil", align_ne: "Neutral Evil", align_ce: "Chaotic Evil"
  }
};

let currentLang = safeStorage.getItem('dnd_lang') || 'pt-BR';

function initLanguage() {
  document.querySelectorAll('.lang-select').forEach(sel => sel.value = currentLang);
  applyLanguage(currentLang);
}

function changeLanguage(lang) {
  currentLang = lang;
  safeStorage.setItem('dnd_lang', lang);
  document.querySelectorAll('.lang-select').forEach(sel => sel.value = lang);
  applyLanguage(lang);

  if (typeof currentId !== 'undefined' && currentId && typeof characters !== 'undefined') {
    const char = characters.find(c => c.id === currentId);
    if (char && typeof renderSpellSlots === 'function') {
      renderSpellSlots(char);
    }
  }

  if (typeof renderList === 'function' && (!currentId)) {
    renderList();
  }
}

function getTranslation(key) {
  return translations[currentLang][key] || key;
}

function applyLanguage(lang) {
  const t = translations[lang];
  if (!t) return;

  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key]) el.textContent = t[key];
  });

  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (t[key]) el.placeholder = t[key];
  });

  document.querySelectorAll('[data-i18n-title]').forEach(el => {
    const key = el.getAttribute('data-i18n-title');
    if (t[key]) el.title = t[key];
  });
}
